apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
stringData:
  SMTP_HOST: maildev
  SMTP_PORT: "1025"
  SMTP_SECURE: "false"
  SMTP_USER: ""
  SMTP_PASS: ""
  SMTP_FROM: portal@example.com
